title: Discord Webhook | whdzera
email: whdzera@gmail.com
baseurl: "/jekyll-discord-webhook" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: whdzera
github_username:  rokhimin/jekyll-discord-webhook

permalink: /:title.rb
files: "/jekyll-discord-webhook"