title: Discord Webhook | whdzera
email: whdzera@gmail.com
baseurl: "/discord-webhook" 
url: "" 
twitter_username: whdzera
github_username:  rokhimin/discord-webhook

permalink: /:title.rb
files: "/discord-webhook"
